apiVersion: v1
kind: Service
metadata:
  labels:
    app: position-service
  name: position-service
spec:
  ports:
    - name: "18090"
      port: 18090
      targetPort: 18090

  selector:
    app: position-service
